# Use a imagem base adequada para sua aplicação
FROM nginx:alpine

# Copiar o conteúdo do diretório local para dentro do container
COPY . /usr/share/nginx/html

# Copia o arquivo de configuração personalizado para o diretório de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Nenhuma modificação adicional necessária, nginx já é iniciado automaticamente
EXPOSE 80